version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"

  airflow:
    image: apache/airflow:2.7.1-python3.9
    container_name: airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  dbt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dbt
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: ["sleep", "infinity"]  # Keeps the container running for interactive dbt use
